apiVersion: v1
kind: Service
metadata:
  name: vvce-client
spec:
  selector:
    app: vvce-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vvce-server
spec:
  selector:
    app: vvce-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
