apiVersion: v1
kind: Service
metadata:
  name: vvce-server
  labels:
    app: vvce-server
spec:
  type: ClusterIP
  selector:
    app: vvce-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
